### ISSUE TITLE
Missing conda enviroments

### ISSUE THREAD

**Issue by jwdebelius** [biocore/oecophylla#62]
This is long. Bear with me.

I installed the using the current (Thurs 3:30 pm) install script, and ran the test data.

```bash
source activate oecophylla
snakemake all --cores 2 --configfile config.yaml
```

I have some warnings:
```
Relative file path './test_data/test_reads/S22282_S102_L001_R1_001.fastq.gz' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
```

And then, I go to run `rule qc_atropos` and get an error message.

```
rule qc_atropos:
    input: results/raw/sample_S22282/combined_reads/sample_S22282.R1.fastq.gz, results/raw/sample_S22282/combined_reads/sample_S22282.R2.fastq.gz
    output: results/qc/sample_S22282/atropos_trimmed/sample_S22282.trimmed.R1.fastq.gz, results/qc/sample_S22282/atropos_trimmed/sample_S22282.trimmed.R2.fastq.gz
    log: results/qc/logs/qc_atropos.sample=[sample_S22282].log
    jobid: 10
    benchmark: benchmarks/qc/qc_atropos.sample=[sample_S22282].txt
    wildcards: trimmer=atropos, sample=sample_S22282
    threads: 2

Traceback (most recent call last):
  File "/Users/jdebelius/miniconda2/envs/oecophylla/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/jdebelius/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 151, in main
    activate.main()
  File "/Users/jdebelius/miniconda2/lib/python2.7/site-packages/conda/cli/activate.py", line 160, in main
    prefix = prefix_from_arg(sys.argv[3], shelldict=shelldict)
  File "/Users/jdebelius/miniconda2/lib/python2.7/site-packages/conda/cli/activate.py", line 60, in prefix_from_arg
    prefix = locate_prefix_by_name(context, arg.replace('/', os.path.sep))
  File "/Users/jdebelius/miniconda2/lib/python2.7/site-packages/conda/base/context.py", line 580, in locate_prefix_by_name
    raise CondaEnvironmentNotFoundError(name)
conda.exceptions.CondaEnvironmentNotFoundError: Could not find environment: oecophylla-qc .
```

When I check my conda list, I have `oecophylla`, but not `oecophylla-qc`, `oecophylla-assembly`, etc. 

Do we need to update the conda installation script to allow the installation of each enviroment needed to execute the rules/script?

**Comment by antgonza** [comment]
had the same issue this morning and realized that I didn't follow the instructions:https://github.com/biocore/oecophylla#installation  ... basically, run: `bash install.sh`.

**Comment by jwdebelius** [comment]
Okay, so I uninstall. Re-install. Then, I get...

```
bash install.sh
Using Anaconda Cloud api site https://api.anaconda.org
Executing oecophylla/assemble/assemble.sh... failed.
```

**Comment by wasade** [comment]
@jwdebelius is this local on mac?

**Comment by afvrbanac** [comment]
I have the same problem installing on barnacle

**Comment by wasade** [comment]
Have a mod coming momentarily to expose the log info

**Comment by antgonza** [comment]
any updates with this? I'm getting the same error but if I run the actual command: ` conda env create --name oecophylla-assemble -f oecophylla/assemble/assemble.yaml` if works fine. Perhaps is an issue with moving the the right folder in the install?
